### ISSUE TITLE
String.include is NoMethodError on Ruby 2.0.0

### ISSUE THREAD

**Issue by k-ta-yamada** [k-ta-yamada/renc#14]
https://travis-ci.org/k-ta-yamada/renc/jobs/198695729#L738

~~~
/home/travis/build/k-ta-yamada/renc/lib/renc.rb:13:in `block in <module:Renc>': private method `include' called for String:Class (NoMethodError)
	from /home/travis/build/k-ta-yamada/renc/lib/renc.rb:13:in `each'
	from /home/travis/build/k-ta-yamada/renc/lib/renc.rb:13:in `<module:Renc>'
	from /home/travis/build/k-ta-yamada/renc/lib/renc.rb:4:in `<top (required)>'
	from /home/travis/build/k-ta-yamada/renc/spec/spec_helper.rb:10:in `require'
	from /home/travis/build/k-ta-yamada/renc/spec/spec_helper.rb:10:in `<top (required)>'
	from /home/travis/build/k-ta-yamada/renc/spec/benchmark_spec.rb:1:in `require'
	from /home/travis/build/k-ta-yamada/renc/spec/benchmark_spec.rb:1:in `<top (required)>'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
/home/travis/.rvm/rubies/ruby-2.0.0-p598/bin/ruby -I/home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/lib:/home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-support-3.5.0/lib /home/travis/build/k-ta-yamada/renc/vendor/bundle/ruby/2.0.0/gems/rspec-core-3.5.4/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
~~~

**Comment by k-ta-yamada** [comment]
~~~
Failures:
  1) Renc benchmark Hash 
     Failure/Error: let(:obj) { key.zip(val).to_h }
     
     NoMethodError:
       undefined method `to_h' for #<Array:0x00000006607d08>
     # ./spec/benchmark_spec.rb:12:in `block (3 levels) in <top (required)>'
     # ./spec/benchmark_spec.rb:15:in `block (5 levels) in <top (required)>'
     # ./spec/benchmark_spec.rb:15:in `block (4 levels) in <top (required)>'
     # ./spec/benchmark_spec.rb:16:in `block (4 levels) in <top (required)>'
Finished in 0.32053 seconds (files took 5.75 seconds to load)
49 examples, 1 failure
~~~

**Comment by k-ta-yamada** [comment]
`#to_h` is >= 2.1.0

**Comment by k-ta-yamada** [comment]
> "I think so -- Ruby recently changed include from private to public, and it might have been in…" — Justin Weiss http://disq.us/p/y6qxzu


> Ruby 2.0.0 リファレンスマニュアル > ライブラリ一覧 > 組み込みライブラリ > Moduleクラス > include (private)
https://docs.ruby-lang.org/ja/2.0.0/method/Module/i/include.html

> Ruby 2.1.0 リファレンスマニュアル > ライブラリ一覧 > 組み込みライブラリ > Moduleクラス > include
https://docs.ruby-lang.org/ja/2.1.0/method/Module/i/include.html

**Comment by k-ta-yamada** [comment]
fixup
